-- 037: Carga de datos reales de empresas (clientes)
-- Borra datos antiguos e inserta los 368 registros del CSV del holding

BEGIN;

-- 1. Hacer "tipo" nullable (muchas empresas no tienen tipo en el CSV)
ALTER TABLE empresas ALTER COLUMN tipo DROP NOT NULL;

-- 2. Hacer "cif" nullable y quitar UNIQUE (empresas extranjeras sin CIF + duplicados pendientes de revisar)
ALTER TABLE empresas ALTER COLUMN cif DROP NOT NULL;
ALTER TABLE empresas DROP CONSTRAINT IF EXISTS empresas_cif_key;
DROP INDEX IF EXISTS empresas_cif_key;

-- 3. Borrar datos existentes (respetar orden de FK)
DELETE FROM asignaciones;
DELETE FROM ordenes_trabajo_personas;
DELETE FROM ordenes_trabajo;
DELETE FROM proyectos_departamentos;
DELETE FROM proyectos;
DELETE FROM contactos_empresas;
DELETE FROM empresas;

-- 4. Insertar empresas reales
INSERT INTO empresas (
  nombre_legal, estado, tipo, tipo_cliente, tipo_conocido, estado_prospecto,
  sector, web, fecha_primer_contrato, notas, cif, nombre_interno,
  calle, ciudad, provincia, codigo_postal, pais
) VALUES
('AIMSA GRUPO TEXTIL S.L', 'Cliente', 'Fabricante', 'Servicio', NULL, NULL, 'MODA', NULL, NULL, NULL, 'B96953765', 'Ysabel Mora', 'C/ Ronda Sequia de Meses 3 Polígono Industrial de Meses', 'Xativa', 'Valencia', '46800', 'España'),
('ALL NUTRITION COMERCIAL LIMITADA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'XEXX010101000', 'All Nutrition', 'Av. Del Valle Sur 577 oficina 704', '44610 Santiago Huechuraba Chile', 'Chile', NULL, 'Chile'),
('ARKOSLIGHT S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98591381', 'ArkosLight', 'Calle N S/N - Pol Ind El Oliveral', 'Ribarroja del Turia', 'Valencia', '46394', 'España'),
('AUTOMATISMOS ESMA SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B82471640', 'ESMA', 'Avda Castilla - Nº32 Nave 9', 'San Fernando de Henares', 'Madrid', '28830', 'España'),
('CESTA DE LOS ABETOS SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40577363', 'Cestón Abetos', 'Carretera Masía del Juez 64', 'Torrente', 'Valencia', '46900', 'España'),
('CLICKTECH SOLUTIONS LTD', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ClickTech', '7 Castle Quay Castle Boulevard', 'Nottingham NG7 1FW', NULL, NULL, NULL),
('Connectif Artificial Intelligence S.L.', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B05509641', 'Connectif', 'Campus Univ. de Espinardo 7 Edificio CEEIM Mód 1', 'Murcia', 'Murcia', '30100', 'España'),
('CORPORACION TURISTICA CURACAO BV', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '153268', 'Atlantic City', 'Fransche Bloemweg 4', 'Curazao', NULL, NULL, 'España'),
('ENCOM GAMES SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98505688', 'ENCOM', 'José Pérez Fuster Metge', 'VALENCIA', 'Valencia', '46007', 'España'),
('ENERGIA COLECTIVA S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98670003', 'Lucera', 'C/ Don Juan de Austria nº 28 Pta 4', 'Valencia', 'Valencia', '46002', 'España'),
('ENRIQUE RUBIO POLO S.L.U', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97643308', 'Rubio', 'Coeters', 'Paterna', 'Valencia', '46980', 'España'),
('EQUIPE CERAMICAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B12512315', 'NAIS', 'CTRA. CV-190 KM 9', 'FIGUEROLES', 'Castellón', '12122', 'España'),
('FUNDACION OXFAM INTERMON', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G58236803', 'Oxfam', 'DMOURA4 calle Treball', 'Barcelona', 'Barcelona', '8019', 'España'),
('IBERINFORM INTERNATIONAL S.A', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A28382927', 'Iberinform', 'Menendez Alvaro', 'Madrid', 'Madrid', '28045', 'España'),
('Icarus Media Digital', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IE3412681FH', 'Icarus', 'Arthur Cox Building Earlsfort Terrace', '579087 Dublin Dublin', NULL, NULL, NULL),
('LG ELECTRONICS ESPAÃA S.A.U.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A-81304487', 'LG', 'Calle Chile nº 1', 'Las Rozas', 'Madrid', '28290', 'España'),
('K-TUIN SISTEMAS INFORMATICOS S.A.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A50578772', 'K-Tuin', 'Orense 52', 'Madrid', 'Madrid', '28020', 'España'),
('KPI Campaigns Ltd.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '24440 IBC 2018', 'KPI', 'Suite 305 Griffith Corporate Centre Beachmont', 'P.O.Box 15 Kingstown St.Vincent & the Grenadines', NULL, NULL, NULL),
('LYC TIENDAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B53663076', 'Hispanitas', 'Avenida Libertat 44', 'Petrer', 'Alicante', '3610', 'España'),
('MENTES EXPERTAS COMUNICACIONES S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B92439124', 'Mentes Expertas', 'Calle Puerto 14', 'Malaga', 'Malaga', '29016', 'España'),
('NRT MONTEROS MARBELLA S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67459685', 'Prime Invest Cugat', 'Cami de Ca N´ametllers nº6 - edif 1 - pl 5ª- 6ª', 'Sant Cugat del Vallés', 'Barcelona', '8195', 'España'),
('ONLINE PROSPECT LIMITED', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1762534', 'Online Prospect', 'Unit 1109 11/F Kowloon Centre 33 Ashley Road', 'Tsim Sha Tsui Kowloon', NULL, NULL, NULL),
('PARSONA CORPORACION SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B71145999', 'Parques Solares', 'Parque Tomas Caballero 1 Bajo', 'Pamplona', 'Navarra', '31005', 'España'),
('PRIME INVERSIONES INMOBILIARIAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86320249', 'Prime Invest Marb', 'Centro de Negocios Oasis Business Center Oficina Nº 1 1ª p', 'Málaga', 'Malaga', '29600', 'España'),
('PROCEED YOUR COMMERCE S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88390984', 'The Masie', 'Avenida Menendez Pelayo Nº 36 - Bajos - Puerta CEN', 'Madrid', 'Madrid', '28007', 'España'),
('SBM CIENCIAS PARA LA VIDA S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87613469', 'SBM España', 'C/ Pintor Sorolla 31 1ª', 'Valencia', 'Valencia', '46002', 'España'),
('Share focus Ltd', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2336349', 'Share Focus', '2003 20/f Tower 5 China Hong Kong City 33 Canton Road Kowl', NULL, NULL, NULL, NULL),
('SINTAC Recycling S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98219074', 'SINTAC', 'Calle 200 42', 'La Canyada Paterna', 'Valencia', '46182', 'España'),
('SKLUM HOME AND DECO S.L.U.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98845936', 'SKLUM', 'Partida Tancaes S/N', 'Vilallonga', 'Valencia', '46720', 'España'),
('SMART SOFTWARES S.A.', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Smart Softwares', 'Cours de Rive 4 CH-6601030019-1', '1204 Genève Switzerland', NULL, NULL, NULL),
('SNA EUROPE INDUSTRIES IBERIA S.A', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A20516233', 'Bahco', 'ANTIGUA CARRETERA ALTUBE KM 5', 'Vitoria', 'Alava', '1196', 'España'),
('SOMOS VENTA ONLINE S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98565443', 'TopMueble', 'C/ Enlace de Verola S/N', 'Sollana', 'Valencia', '46430', 'España'),
('THE FLOW LAB S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42600320', 'Partylosophy', 'Calle Maestro Guerrero 6', 'Ibi', 'Alicante', '3440', 'España'),
('UPPER CLASS RENTAL SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98924327', 'HQ Rooms', 'C/ San Vicente Martir 141 1 planta', 'Valencia', 'Valencia', '46007', 'España'),
('VALENCIA CLUB DE FUTBOL S.A.D.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46050217', 'Valencia CF', 'Plaza Valencia CF 2', 'Valencia', 'Valencia', '46010', 'España'),
('Vidacaixa S.A.U de Seguros y Reaseguros', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A58333261', 'VidaCaixa', 'Paseo de la Castellana 189', 'Madrid', 'Madrid', '28029', 'España'),
('WOODS & GO DESIGN S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98944986', 'Create', 'C/ Poligono 4 P18', 'BENIARJO', 'Valencia', '46722', 'España'),
('WORLD VISA LIMITED', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'World Visa', 'Atlantic House Circular Road Douglas', 'IM1 1AG Isle of Man', NULL, NULL, NULL),
('PRIBUCOL S.A.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A83862052', 'Colchon Express', 'del Mar Tirreno', NULL, NULL, NULL, NULL),
('SBM LIFE SCIENCE S.r.l.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '9586670961', 'SBM Italia', 'Montefeltro', 'Milán', NULL, '20156', 'España'),
('ACTIU BERBEGAL Y FORMAS S.A', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A03137874', 'Actiu', 'Parque Tecnológico Actiu Autovía CV-80', 'CASTALLA', 'Alicante', '3420', 'España'),
('DIGITALMENTA MARKETING', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42777821', 'DMM', NULL, NULL, 'Valencia', NULL, 'España'),
('CEESI ASESORES', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96184478', 'Flexigo', 'Ceramistes', 'ALBORAYA', 'Valencia', '46120', 'España'),
('SONOSUITE SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B17943986', 'Sonosuite', 'TRAFALGAR', 'BARCELONA', 'Barcelona', '8010', 'España'),
('MENTA INNOVATIONS S.L.', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98786486', 'DM ESP', 'San Valero 7', 'Valencia', 'Valencia', '46005', 'España'),
('AUREA PEOPLE S.L.', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40610214', 'Aurea People', 'San Valero 7', 'Valencia', 'Valencia', '46005', 'España'),
('ZAZEN DIGITAL S.L', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88249529', 'BidBalance', 'Pablo Ruiz Picasso', 'MADRID', 'Madrid', '28020', 'España'),
('MY WAY VENTURES S.L.', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42929109', 'MWV', 'San Valero 7', 'Valencia', 'Valencia', '46005', 'España'),
('DIGITAL MENTA MEXICO SA DE CV', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DMM220217727', 'DM MEX', 'De Las Americas 1254/Piso 17 Country Club', NULL, NULL, NULL, NULL),
('LEASK S.L.U', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73287740', 'PowerPlanet', 'Balsón de Guillén 8', 'TOTANA', 'Murcia', '30850', 'España'),
('CNQR AdTech LTD', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IE3608833RH', 'CNQR', 'Northwood Santry Dublin 9 D09 C6X8', NULL, NULL, NULL, NULL),
('Delibreads Europe S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98240369', 'Delibreads', 'Les Carrases parcela D', 'LLIRIA', 'Valencia', '46160', 'España'),
('Black & White Media', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '3072986', 'Black&White', 'WANCHAI HONG-KONG', NULL, NULL, NULL, NULL),
('EUROLEX S.A', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CHE262557554', 'Eurolex', 'Rue J. Imbert-Galloix 2', 'Geneve', NULL, NULL, NULL),
('ASOCIACION DE DISEÃADORES DE MODA COMUNIDAD VALENCIANA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G97352942', 'CLEC', 'Padre Jofre', 'VALENCIA', 'Valencia', '46007', 'España'),
('PACO PERFUMERIAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46930541', 'Paco Perfumeria', 'C Nº6 - E squina Calle H', 'Ribaroja del Turia', 'Valencia', '46394', 'España'),
('PEPE NAVARRO', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46432852', 'Herbolario', 'Arzobispo Mayoral', 'VALENCIA', 'Valencia', '46002', 'España'),
('WAYCO IDEAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98549959', 'WAYCO', NULL, 'VALENCIA', 'Valencia', '46005', 'España'),
('Fairtrade Ibérica', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G20877437', 'Fairtrade', 'Alameda', 'MADRID', 'Madrid', '28014', 'España'),
('DROP SEND S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01671510', 'Mosquiteras', 'CAMI NOU', 'BENETUSSER', 'Valencia', '46910', 'España'),
('CROSSMEDIA LTD', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GB018340V', 'Crossmedia', 'IM1 1AG Isle of Man', 'Isle of Man', NULL, NULL, NULL),
('LEVANTE UNION DEPORTIVA S.A.D.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46064242', 'Levante UD', 'San Vicente de Paul', 'VALENCIA', 'Valencia', '46019', 'España'),
('MAICERIAS ESPAÃOLAS S.A', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46048815', 'DACSA', 'Barcelona', 'ALMÃSSERA', 'Valencia', '46132', 'España'),
('CAMPERDAYS GmbH', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DE363892876', 'Camperdays', 'Holzmarkt 2a', NULL, NULL, '50676', 'España'),
('INDUSTRIAS DE OPTICA PRATS S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B08233108', 'Prats ES', 'VIGIL', 'MADRID', 'Madrid', '28052', 'España'),
('VOLLMOND', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Vollmond', NULL, NULL, 'Valencia', NULL, 'España'),
('PRATS LUSITANIA IOSA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '503094854', 'Prats PT', NULL, 'Alges Lisboa', NULL, '1495', 'España'),
('MEDIA HUNTERS', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '307298', 'Media Hunters', NULL, 'Hong Kong', NULL, NULL, NULL),
('FRESCO PODOLOGIA S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B58618323', 'Fresco', 'SICILIA', 'BARCELONA', 'Barcelona', '8013', 'España'),
('ADELANTE HOUSE ESPAÃA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42658070', 'Adelante Homes', 'Lluca', 'JAVEA', 'Alicante', '3730', 'España'),
('CROWDFARMING S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87952651', 'Crowdfarming', 'Anzuola', 'MADRID', 'Madrid', '28002', 'España'),
('MOLENDUM INGREDIENTS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B49279649', 'Natur Dacsa', 'Industrial el Roto (La Milana)', 'CORESES', 'Zamora', '49530', 'España'),
('TRANS SABATER S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46351300', 'Trans Sabater', 'dels Fogainers S/Nº', 'RIBA-ROJA DE TURIA', 'Valencia', '46190', 'España'),
('WALABI VALCARABAN S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42962951', 'Walabi', 'Martino', 'BENIPARRELL', 'Valencia', '46469', 'España'),
('ISMONA EUROPA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B55284996', 'Manicura24', 'Francia', 'SANT JULIA DE RAMIS', 'Girona', '17481', 'España'),
('Job Companion SA', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CHE333545259', 'Job Companion', 'Cours de Rive 4', NULL, NULL, NULL, NULL),
('MUSAL DISTRIBUCIONES GROUP S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B16799371', 'Musal', 'Diego de León', 'MADRID', 'Madrid', '28006', 'España'),
('ANDREU WORLD S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40634453', 'Andreu World', 'Los Sauces', 'CHIVA', 'Valencia', '46370', 'España'),
('ECG MEDICA S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46138632', 'Ascires', 'Colón', 'VALENCIA', 'Valencia', '46004', 'España'),
('EVENTOS KENTIA SOCIEDAD LIMITADA.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Isla Despedidas', 'Valencia', NULL, 'Valencia', NULL, 'España'),
('CASINO CIRSA VALENCIA SOCIEDAD ANONIMA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46114336', 'Casino Cirsa', 'DE LES CORTS VALENCIANES', NULL, 'Valencia', '46015', 'España'),
('CARDONA BALLESTER S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98509425', 'Dolls&Dolls', 'MOSAIQUERS', 'MELIANA', 'Valencia', '46133', 'España'),
('PATAPATO APP SOCIEDAD LIMITADA.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40522823', 'Patapato', 'DOCTOR SANCHIS SIVERA', NULL, 'Valencia', '46008', 'España'),
('GÃMEZ BAÃULS SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96714753', 'Gente Urbana', 'Matias Perelló', NULL, 'Valencia', '46005', 'España'),
('Assembly AI SA', 'Otros', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CHE27033269', 'Assembly', 'Cours de Rive', NULL, NULL, NULL, NULL),
('GERMINATS TUGAS', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B63383509', 'TUGAS', 'de Can Borí nau 5-6', 'Sant Climent de Llobregat', 'Barcelona', '8849', 'España'),
('PANSFOOD SA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A58634726', 'Pans', 'Cerdanya', 'Sant Cugat del Vallès', 'Barcelona', '8173', 'España'),
('LABORATORIES SVR', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B63976385', 'Labs SVR', 'Roger de Lluria', 'Barcelona', 'Barcelona', '8037', 'España'),
('FOODSTATION SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B82694241', 'Foodstation', 'Cerdanya no', 'Sant Cugat del Vallès', 'Barcelona', '8173', 'España'),
('ADELUP DENTAL S.L.P', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87927539', 'Adelup Dental', 'Espronceda', 'Madrid', 'Madrid', '28003', 'España'),
('JOYERIAS TOUS', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A25039199', 'TOUS', 'Vic al Guix', 'Manresa', 'Barcelona', '8243', 'España'),
('MONTAMAR SERVCIOS PUBLICITARIOS SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98285919', 'Montamar', 'CAVITE', 'Valencia', 'Valencia', '46011', 'España'),
('NUTRITION&SANTE IBERIA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B63175715', 'Notrition Santé', 'de Gracia', 'Barcelona', 'Barcelona', '8002', 'España'),
('SANTA EULALIA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A08031734', 'Santa Eulalia', 'de Gracia', 'Barcelona', 'Barcelona', '8008', 'España'),
('BRITA IBERIA SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B63039796', 'Brita Iberia', 'València', 'Barcelona', 'Barcelona', '8009', 'España'),
('COM. PROP. C.C. La Maquinista', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'H62322771', 'La Maquinista', 'Potosí', 'Barcelona', 'Barcelona', '8030', 'España'),
('GRENERGY RENOVABLES', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A85130821', 'Grenergy', 'Rafael Botí', NULL, 'Madrid', '28023', 'España'),
('LAFORASTERA FILMS', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B19979319', 'LAFORASTERA', 'de GRacia', 'Barcelona', 'Barcelona', '8005', 'España'),
('Com. Prop. CC. Les Glories', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'H81520298', 'LES GLORIES', 'Diagonal', 'Barcelona', 'Barcelona', '8005', 'España'),
('SHHH SILENCIOSA SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B10592202', 'SHHH SILENCIOSA', 'Mercader', 'Barcelona', 'Barcelona', '8008', 'España'),
('Villarreal CF S.A.D', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A12362927', 'VILLARREAL', 'Miralcamp s/n', 'Vila-real', 'Castellón', '12540', 'España'),
('SANITAS MAYORES SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B58937178', 'SANITAS', 'Ribera del Loira', 'Madrid', 'Madrid', NULL, 'España'),
('COMPAC CORPORATE', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96925342', 'COMPAC', 'Comarques del PaÃ­s ValenciÃ', 'Quart de Poblet', 'Valencia', '46930', 'España'),
('BODEGAS TORRE ORIA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46922662', 'TORRE ORIA', 'Pontón-Utiel km 3 Derramador Valencia', NULL, 'Valencia', '46390', 'España'),
('HR AI Solutions Factory S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88375639', 'VELORA', 'San Marino 2 - BL J Pta a Plt 4', NULL, 'Madrid', '28022', 'España'),
('NARASON DIGITAL S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B75448084', 'NARASON', 'Castellana', NULL, 'Madrid', '28046', 'España'),
('Fundació Privada Amics del MNAC', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G64140361', 'AMICS MNAC', 'Palau Nacional. Parc de Montjuïc', 'Barcelona', 'Barcelona', '8038', 'España'),
('CREATIVE JUMP LAB S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B16399404', 'KAUAI', 'Sant Pere', 'Barcelona', 'Barcelona', NULL, 'España'),
('Incyte Bioscience Iberia', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86592219', 'INCYTE', 'de la Encina', 'Tres Cantos', 'Madrid', '28760', 'España'),
('GLOCALLY COMUNICACIÃN INTEGRAL S.L. -', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87337333', 'GLOCALLY', 'GUZMAN EL BUENO', 'Madrid', 'Madrid', '28003', 'España'),
('NOE PRADES STUDIO SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B44652709', 'NOE PRADES', 'Via Laietana', 'Barcelona', 'Barcelona', '8003', 'España'),
('MUSEU NACIONAL D''ART DE CATALUNYA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Q5856250E', 'MUSEU ART CAT', 'Palau Nacional- Parc de Montjuïc', 'Barcelona', 'Barcelona', '8038', 'España'),
('USHUAIA DESIGN S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98658990', 'ANARTXY', 'de la Creu', NULL, 'Valencia', '46185', 'España'),
('RK BY REALMARK INMOBILIARIA S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40539827', 'RK', 'Adolfo Azcárraga', NULL, 'Valencia', '46024', 'España'),
('VICHY CATALAN SA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A08000366', 'VICHY CATALAN', 'Roger de Llúria', 'Barcelona', 'Barcelona', '8037', 'España'),
('BUGANVILLASOMNIS SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66482365', 'BUGANVILLASOMNI', 'Pellaires nº 30 Barcelona', 'Barcelona', 'Barcelona', '8019', 'España'),
('CIM GRUPO DE FORMACION Y DESARROLLO SLU', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B21641006', 'CIM', 'Arzobispo Mayoral', 'Valencia', 'Valencia', '46002', 'España'),
('MOVISTAR PROSEGUR ALARMAS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87222006', 'PROSEGUR', 'Herberto Gut', 'Madrid', 'Madrid', '28007', 'España'),
('SAYFOOD Marketing S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B70939962', 'SAYFOOD', 'Marvá', 'Valencia', 'Valencia', '46007', 'España'),
('Brooklyn Fitboxing International SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86989068', 'BROOKLYN', 'sabel Colbrand', 'Madrid', 'Madrid', '28050', 'España'),
('ACTYCREA 110 SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87455820', 'ACTYCREA', 'GENERAL ZABALA', 'MADRID', 'Madrid', '28002', 'España'),
('ASUS Europe B.V.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NL817716889B01', 'ASUS', 'Paasheuvelweg 25', 'BP Amsterdam', NULL, '1105', 'España'),
('FundaciÃ³ BancÃ ria "La Caixa"', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G58899998', 'FUN LA CAIXA', 'Diagonal', 'Barcelona', 'Barcelona', '8019', 'España'),
('Cinco Tintas SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66410556', 'CINCO TINTAS', 'Diagonal', 'Barcelona', 'Barcelona', '8037', 'España'),
('GAOLANIA SERVICIOS S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98717457', 'GAOLANIA', 'COLON', 'Valencia', 'Valencia', '46004', 'España'),
('GRUPO LOGISTICO SUARDIAZ S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B83135400', 'SUARDIAZ', 'AYALA', 'Madrid', 'Madrid', '28001', 'España'),
('TESA PRECISION MEASUREMENT INSTRUMENTS SARL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CHE474531982', 'TESA', NULL, NULL, NULL, NULL, NULL),
('DIPUTACIO DE BARCELONA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P0800000B', 'DIP BARNA', 'Cataluña', 'Barcelona', 'Barcelona', '8008', 'España'),
('MARVIMUNDO', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MARVIMUNDO', NULL, NULL, NULL, NULL, NULL),
('DR. ROBERTS', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DR ROBERTS', NULL, NULL, NULL, NULL, NULL),
('VICCARBE HABITAT, S.L', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96783907', 'VICCARBE', 'P.I. Norte, Camí del Racó, 23', 'Beniparrell', 'Valencia', '46469', 'España'),
('AMADA BANUS OCIO, S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B75904011', 'SAN BERNABE', 'AV. los Acebos. Artola Alta , OTR 1, 1, C', 'Malaga', 'Malaga', '29604', 'España'),
('AVANQUA OCEANOGRAFIC, S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98725252', 'OCEANOGRAFIC', 'Gran Vía Marqués del Turia, 19', 'Valencia', 'Valencia', '46005', 'España'),
('CASINO NUEVA ANDALUCIA MARBELLA, S.A.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A29043064', 'CASINO MARBELLA', 'Casino Marbella - Bajos Hotel Hard Rock Marbella S/N', 'Malaga', 'Malaga', '29660', 'España'),
('UNIVERSITAT INTERNACIONAL VALENCIANA-VALENCIAN INTERNATIONAL UNIVERSITY, S.L. (VIU)', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98585797', 'VIU', 'PINTOR SOROLLA 21', 'Valencia', 'Valencia', '46002', 'España'),
('Instituto de Tecnología de Valencia', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01858620', 'INST TEC VALENCIA', 'CL. Doctor Josep Juan Dómine, 1', 'Valencia', 'Valencia', '46002', 'España'),
('VIVOFACIL S.A.U', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A82277963', 'VIVOFACIL', 'CL. Miguel Yuste, 23, 2', 'Madrid', 'Madrid', '28037', 'España'),
('ORANGE ESPAGNE, S.A.U.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A82009812', 'LUCERA', 'Parque Empresarial la Finca Edificio 5, Paseo del Club Depor', 'Pozuelo de Alarcón', 'Madrid', '28223', 'España'),
('AVAESEN', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G97735302', 'AVAESEN', 'XÃ tiva, 15-16A', 'Valencia', 'Valencia', '46002', 'España'),
('LUMERIS L.L.C-FZ', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LUMERIS', NULL, NULL, NULL, NULL, NULL),
('HAIR INSPIRA CORP, SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01878107', 'HAIR', 'SARRIA 60', 'Barcelona', 'Barcelona', '8029', 'España'),
('NEWLING CONSULTING&COMMUNICATIONS SPAIN SA', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A81867202', 'NEWLING', NULL, NULL, NULL, NULL, 'España'),
('IMAGINE FOREVER SL', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B24902843', 'IMAGINE', NULL, NULL, NULL, NULL, 'España'),
('Funeraria San Bernabé S.L.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B29147378', 'SAN BERNABE', 'Cementerio virgen del Carmen Carretera de Ojén S/N', 'Marbella', 'Malaga', '29600', 'España'),
('CREATIVE BEAUTY PRODUCTS, S.L.U.', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B62809512', 'BEAUTY PRODUCTS', NULL, NULL, NULL, NULL, 'España'),
('ESPECIALIDADES DENTALES KALMA, S.A', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A28491777', 'KALMA', NULL, NULL, NULL, NULL, 'España'),
('SKIN TECH PHARMA GROUP SLU', 'Cliente', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B17470261', 'SKIN', NULL, NULL, NULL, NULL, 'España'),
('L''ESTIL DELS MENUTS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98045347', 'ESTIL MENUT', 'Avenida Barcelona 92 33', 'Torrent', 'Valencia', '46900', 'España'),
('11824 Servicio Información Telefónica S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01992387', '11824 Servicio', 'Calle Velázquez No 27 1o ext', 'Madrid', 'Madrid', '28001', 'España'),
('AAO OPTICO S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A78766185', 'AAO OPTICO S.A', 'Paseo Castellana nº 89 pl 11', 'Madrid', 'Madrid', '28046', 'España'),
('AdTech Media Ltd GB 289 8974 05', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AdTech Media Lt', 'Sunderland Software Centre Tavistock Place', 'SR1 1PB Sunderland England', NULL, NULL, 'Reino Unido'),
('Agua Mineral San Benedetto S.A.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A81224495', 'Agua Mineral Sa', 'Camino del Pinarejo s/n', 'San Antonio de Requena', 'Valencia', '46390', 'España'),
('ALAIN AFFLELOU AUDIOLOGO S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A87551909', 'ALAIN AFFLELOU', 'Paseo de la Castellana nº 89 Planta 11', 'Madrid', 'Madrid', '28046', 'España'),
('ALAIN AFFLELOU ESPAÃA S.A.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A83759019', 'ALAIN AFFLELOU', 'Paseo de la Castellana nº 89 planta 11ª', 'Madrid', 'Madrid', '28046', 'España'),
('ALL IN DIGITAL MARKETING SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88369178', 'ALL IN DIGITAL', 'Avenida de Bruselas 15 planta 2', 'Alcobendas', 'Madrid', '28108', 'España'),
('ASOCIACION EMPRESARIAL HOTELERA DE GANDIA Y LA SAFOR', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G96527890', 'ASOCIACION EMPR', 'Carrer de la Valldigna 11 Playa de Gandia', 'Gandia', 'Valencia', '46730', 'España'),
('ATRADIUS CREDITO & CAUCION S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A28008795', 'ATRADIUS CREDIT', 'Paseo de la Castellana 4', 'Madrid', 'Madrid', '28046', 'España'),
('AYWA SERVICIOS AMBIENTALES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B90162116', 'AYWA SERVICIOS', 'Gran Vía Marqués del Turia 19', 'Valencia', 'Valencia', '46005', 'España'),
('BACULUM MAYORES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88242623', 'BACULUM MAYORES', 'Calle Gobelas 13 2º', 'Pozuelo de Alarcon', 'Madrid', '28023', 'España'),
('BAMA FOOTBALL GROUP S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40633463', 'BAMA FOOTBALL G', 'Calle Colón 20 pta 13', 'Valencia', 'Valencia', '46004', 'España'),
('BLACK DIVISION S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B02997641', 'BLACK DIVISION', 'Calle Xixona no 3', 'Elche', 'Alicante', '3204', 'España'),
('BLACKCAPE SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96783857', 'BLACKCAPE SL', 'HERNAN CORTES 14', 'VALENCIA', 'Valencia', '46004', 'España'),
('BLADEFAR SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B72171002', 'BLADEFAR', 'Avda Prado De La Feria 37', 'Medina-Sidonia', 'Cadiz', '11170', 'España'),
('Brandsummit sl', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98798648', 'Brandsummit sl', 'C Blanquerias 17 Bajo derecha', 'Valencia', 'Valencia', '46003', 'España'),
('CADIGRAFIA PUBLICIDAD Y COMUNICACION S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B11282969', 'CADIGRAFIA PUBL', 'Calle Ronda de Vigilancia s/nº Edificio Tartesos Local 1', 'Cadiz', 'Valencia', '11011', 'España'),
('CALCONUT S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B04535878', 'CALCONUT S.L', 'Finca M E-2 Pol Ind Riodel', 'Mutxamel', 'Alicante', '3110', 'España'),
('GRUPO CASTILLA PEOPLE S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A43066299', 'GRUPO CASTILLA', 'Calle de la Informática 5', 'Ruidoms', 'Tarragona', '43330', 'España'),
('CASA INTERIOR & QUALITY HOME SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40529687', 'CASA INTERIOR &', 'GV FERNANDO EL CATOLICO 83 BAJO 5', 'Valencia', 'Valencia', '46008', 'España'),
('CENTRO CANALEJAS MADRID S.L.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86092145', 'CENTRO CANALEJA', 'Calle Sevilla 6 3ª planta', 'Madrid', 'Madrid', '28014', 'España'),
('CLAVE DENIA SA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A03740966', 'CLAVE DENIA SA', 'Av d''Alacant 174', 'Bellreguard', 'Valencia', '46173', 'España'),
('CLINICA DEPORTIVA ALTO RENDIMIENTO S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87098877', 'CLINICA DEPORTI', 'Zurbarán 28', 'Madrid', 'Madrid', '28010', 'España'),
('COMUNIDAD CAMPUS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B15947609', 'COMUNIDAD CAMPU', 'Calle Comandante Fontanes nº 1 1º', 'A Coruña', 'A Coruña', '15003', 'España'),
('CRAMBO WIRELESS S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A83884106', 'CRAMBO WIRELESS', 'Calle de Los Torneros 7', 'San Fernando de Henares', 'Madrid', '28830', 'España'),
('DE DIEGO & MATHER FICASSO REAL ESTATE SCP', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J66008053', 'DE DIEGO & MATH', 'Ronda Universitat 29 3-1', 'Barcelona', 'Barcelona', '8007', 'España'),
('COSENTINO GLOBAL S.L.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01966597', 'COSENTINO GLOBA', 'Ctra. A334 Baza-Huércal Overa Salida 60 Parque Industrial', 'Cantoria', 'Almeria', '4850', 'España'),
('CUTERA SPAIN S L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B83570473', 'CUTERA SPAIN S', 'Avenida Diagonal 429 Pl 3', 'Barcelona', 'Barcelona', '8036', 'España'),
('CREAPOLIS PARC DE LA CREATIVITAT S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A63918072', 'CREAPOLIS PARC', 'Av de la Torreblanca 57', 'Sant Cugat del Vallés', 'Barcelona', '8172', 'España'),
('DEMIUM STARTUPS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98514011', 'DEMIUM STARTUPS', 'Calle Ribera nº 1', 'Valencia', 'Valencia', '46002', 'España'),
('DIRELEC GROUP S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98611643', 'DIRELEC GROUP', 'Avda del Carmen 2', 'L''ALQUERIA DE LA COMTESSA', 'Valencia', '46715', 'España'),
('DERMILASER S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97561153', 'DERMILASER S.L', 'Avenida Baleares 4 Esc B pta 24', 'Valencia', 'Valencia', '46023', 'España'),
('MUEBLING S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98538614', 'DOMVONEVENT', 'Oliveral', 'RIBARROJA DEL TURIA', 'Valencia', '46190', 'España'),
('DUCHA CENA Y A DORMIR S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B06976898', 'DUCHA CENA Y A', 'Carretera de las Rozas a Majadahonda 15 1D Urb El Henar', 'Madrid', 'Madrid', '28231', 'España'),
('EASYGOBAND WORLD S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B12984712', 'EASYGOBAND WORL', 'Polígono Estadio nave 18', 'Castellón', 'Castellón', '12004', 'España'),
('EDIFY HOUSES PROPTECH S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42842633', 'EDIFY HOUSES PR', 'Plaza Legión Española 12 acc', 'Valencia', 'Valencia', '46010', 'España'),
('EMBARGOSALOBESTIA S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73702599', 'EMBARGOSALOBEST', 'Calle Isaac Newton nº 3 Parcela 47 Polígono Industrial El', 'Totana', 'Murcia', '30850', 'España'),
('EMBOGA S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A03326121', 'EMBOGA', 'Avenida Libertat 44', 'Petrer', 'Alicante', '3610', 'España'),
('EMUCA S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46154704', 'EMUCA S.A', 'Poligono Industrial E Oliveral c/h 4', 'Ribarroja del Turia', 'Valencia', '46394', 'España'),
('ESCUELA ESPECIALIZADA EN FORMACION MULTIMEDIA Y MARKETING S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B02978369', 'ESCUELA ESPECIA', 'Calle Padre Tomás Montañana 28-1º B', 'Valencia', 'Castellón', '46023', 'España'),
('ESCOLA POSTGRAU I XARXA DE CENTRES D INVESTIGACIO EN INTEL·LIGENCIA ARTIFICIAL FUNDACIO CV', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G16913162', 'ESCOLA POSTGRAU', 'Camí de Vera S/N', 'Valencia', 'Valencia', '46022', 'España'),
('EUROPEAN SOLID STONE S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98814056', 'EUROPEAN SOLID', 'Calle Libreros 3 pta 3 y 4', 'Valencia', 'Valencia', '46002', 'España'),
('EXIM BUSINESS GLOBAL S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B54922257', 'EXIM BUSINESS G', 'Partida Alfatares Nº 57 4', 'Ondara', 'Alicante', '3760', 'España'),
('FLOATUP SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98845928', 'FLOATUP SL', 'Avda del Carmen 2', 'L''ALQUERIA DE LA COMTESSA', 'Valencia', '46715', 'España'),
('FLORA LUSITA Lda', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PT500117110', 'FLORA LUSITA L', 'Rua Santo António Ap. 5 3060-156', '3060 Cantanhede', NULL, NULL, NULL),
('FRESNEL CONTENIDOS Y FORMATOS AUDIVISUALES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98481187', 'FRESNEL CONTENI', 'Calle del Hospital 1 puerta 11 piso 5º', 'VALENCIA', 'Valencia', '46001', 'España'),
('FUNDACION ALAIN AFFLELOU', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G85207330', 'FUNDACION ALAIN', 'PASEO CASTELLANA NUM 89 PLANTA 11', 'MADRID', 'madrid', '28046', 'España'),
('FUNDACIÃN DE LA COMUNIDAD VALENCIANA PARA LA PROMOCIÃN ESTRATÃGICA EL DESARROLLO Y LA INNOVACIÃN U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G98406002', 'FUNDACIÃN DE LA', 'C Juan Verdeguer 16-24', 'Valencia', 'Valencia', '46024', 'España'),
('GLOBAL SMART ACTIVITIES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67180968', 'GLOBAL SMART AC', 'Carretera Sabadell 259 Nave 3', 'Barcelona', 'Barcelona', '8191', 'España'),
('GOLD DIVISION S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B02997625', 'GOLD DIVISION', 'Calle Xixona 3', 'Elche', 'Alicante', '3204', 'España'),
('GRUPO INTERTORRENT S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67949925', 'INTERTORRENT', 'Avenida Al Vedat 180 local 1', 'Torrente', 'Valencia', '46900', 'España'),
('HASSAN GERMAN OZON', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '25391154M', 'HASSAN GERMAN O', 'Calle Roger de Lauria Nº 8 BJ', 'Valencia', 'Valencia', '46002', 'España'),
('FUNDACIÃN PATRONATO JUVENTUD OBRERA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G46102356', 'FUNDACIÃN PATRO', 'C Poeta Ricard Sanmartí-3', 'Valencia', 'Valencia', '46020', 'España'),
('Fundación Social Nest', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G98748510', 'FUND SOCIALNEST', 'Calle Poeta Artola 29', 'Valencia', 'Valencia', '46021', 'España'),
('FUNDACION UNIVERSIDAD CATOLICA DE VALENCIA SAN VICENTE MARTIR', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G97025787', 'FUNDACION UNIVE', 'Calle Quevedo 2', 'Valencia', 'Valencia', '46001', 'España'),
('GESTORIA REINA MILLAN S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B14521652', 'GESTORIA REINA', 'Ctra de Palma del Río A-431 KM 3 Parque Joyero de Córd', 'Córdoba', 'Cordoba', '14005', 'España'),
('Glent Shoes s.l.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86886959', 'Glent Shoes s.l', 'C Velazquez 10 4 izquierda', 'Madrid', 'Madrid', '28001', 'España'),
('FUNDEEN PLATFORM S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87884896', 'FUNDEEN PLATFOR', 'Plaza de Santa Teresa de Jesús 14 1º-1', 'Avila', 'Avila', '5001', 'España'),
('INIA NEURAL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97645980', 'INIA NEURAL S.', 'Calle Guillem de Castro 46', 'Valencia', 'Valencia', '46001', 'España'),
('INSTALACIONES HIDALGAS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86036019', 'INSTALACIONES H', NULL, 'Madrid', 'Madrid', '28004', 'España'),
('IMRICART MADRID MEDICAL CENTER S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40517047', 'IMRICART MADRID', 'Artes Gráficas 36-esc II-1º', 'Valencia', 'Valencia', '46021', 'España'),
('INSTITUTO MEDICO RICART ALICANTE S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B02717932', 'INSTITUTO MEDIC', 'Artes Gráficas 36-esc II-1º', 'Valencia', 'Valencia', '46021', 'España'),
('JARDEPOT S.A. de C.V.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'JAR111021F14', 'JARDEPOT S.A.', 'Prolongación Calle Vieja 231', '62160 Col. Lomas del Tzompantle Cuernavaca Morelos', NULL, NULL, NULL),
('JOHNSON & JOHNSON S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A28218675', 'JOHNSON & JOHNS', 'Paseo Doce Estrellas 5 7', 'Madrid', 'Madrid', '28042', 'España'),
('INTERNET TOURISM SOLUTIONS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97090138', 'INTERNET TOURIS', 'C Charles Robert Darwin 5 Parque Tecnológico', 'Paterna', 'Valencia', '46980', 'España'),
('KACTUS REPUBLIC S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98991284', 'KACTUS REPUBLIC', 'Calle Pizarro 12 Piso 3º Pta 8', 'Valencia', 'Valencia', '46004', 'España'),
('KONINGCORP SRO', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '7321601', 'KONINGCORP SRO', 'Vlkova 532 8', '130 00 Praha 3', NULL, NULL, NULL),
('LÃNEA MASTERMIND S.L.U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01649300', 'LÃNEA MASTERMIN', 'Camiño do Pontón 25', 'Barbadás', 'Ourense', '32890', 'España'),
('LEVEL LUXURY VILLAS S.L.U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01899103', 'LEVEL LUXURY VI', 'Calle Nicolu Copernic 8 - 20', 'Paterna', 'Valencia', '46980', 'España'),
('Lupo Shops S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B62779947', 'Lupo Shops S.L', 'Calle Mallorca 257', 'Barcelona', 'Barcelona', '8008', 'España'),
('LYUKOS GROUP FZE LLC', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'LYUKOS GROUP FZ', '3059', 'Deira Dubai Branch', NULL, NULL, NULL),
('M. VALENTINA S.A.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FCR190211231', 'M. VALENTINA S.', 'FIDEL VELAZQUEZ 107C', '37160 LEON GUANAJUATO', 'Mexico', NULL, NULL),
('Magic4u S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88366067', 'Magic4u S.L.', 'Calle Paseo de Talleres 3 Nave 166', 'Madrid', 'Madrid', '28021', 'España'),
('MARANALU TRI S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98856206', 'MARANALU TRI S', 'C/ Sierra Helada 17', 'Cullera', 'Valencia', '46400', 'España'),
('MARK JOINT VENTURE S.L.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42616672', 'MARK JOINT VENT', 'Avenida del Rodalet 2', 'Alicante', 'Alicante', '3690', 'España'),
('MASKOKOTAS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98627441', 'MASKOKOTAS S.L', 'Av Generalitat Valenciana 18', 'Massanassa', 'Valencia', '46470', 'España'),
('MEDICOS SIN FRONTERAS', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G58277534', 'MEDICOS SIN FRO', 'C/ Zamora 54', 'Barcelona', 'Barcelona', '8005', 'España'),
('MELEDEM JEP S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98828213', 'MELEDEM JEP S.', 'Marina Real Juan Carlos I Muelle de la Aduana s/nº Edificio', 'VALENCIA', 'Valencia', '46024', 'España'),
('MICUNA S.L.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B-46191094', 'MICUNA S.L.U.', 'Calle Albufera 24', 'Sollana', 'Valencia', '46430', 'España'),
('MIGMONT X S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B06858039', 'MIGMONT X S.L', 'Paseo de Gracia 97 Piso 3-2', 'Barcelona', 'Barcelona', '8008', 'España'),
('MOONFLOWERS', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MOONFLOWERS', '8280 Willow Oaks Corp Drive Ste 600 Fairfax', 'VA 22031', NULL, NULL, NULL),
('MOVE ART MISSION S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66646993', 'MOVE ART MISSIO', 'Calle Sant Pere Més Alt 46 ppal 4', 'Barcelona', 'Barcelona', '8003', 'España'),
('MT2M Media Limited', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'MT2M Media Limi', 'Wework Aldwych House Aldwych GB301714744', 'WC2B 4HN London', NULL, NULL, NULL),
('Muñoz & Arias Sports Lawyers s.l.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40589764', 'Muñoz & Arias S', 'Calle Colon 20 - 13', 'Valencia', 'Valencia', '46004', 'España'),
('NANONEN SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98669690', 'NANONEN SL', 'RONDA DE AUGUSTE I LOUIS LUMIERE 43 NAVE 5 PARQUE TECNOLOGIC', 'PATERNA', 'Valencia', '46980', 'España'),
('NETRIVALS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66612508', 'NETRIVALS S.L.', 'Avenida Meridiana 358 Planta 14', 'Barcelona', 'Barcelona', '8027', 'España'),
('NEW ALTERNATIVE TECHNOLOGIES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73869018', 'NEW ALTERNATIVE', 'Suiza Polígono Industrial Las Salinas', 'Alhama de Murcia', 'Murcia', '30840', 'España'),
('NEW WORK NETWORKING SPAIN S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B64062920', 'NEW WORK NETWOR', 'Calle Consell De Cent 334 1-1', 'Barcelona', 'Barcelona', '8009', 'España'),
('ORSAL S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B46877551', 'ORSAL S.L', 'Polígono Industrial Los Vientos C/Gregal Nave 8', 'Náquera', 'Valencia', '46119', 'España'),
('PC COMPONENTES Y MULTIMEDIA S.L.U.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73347494', 'PC COMPONENTES', 'Avenida Europa Parcelas 2-5 y 2-6 Polígono Industrial Las Sa', 'Alhama de Murcia', 'Murcia', '30840', 'España'),
('PENTAGO XXI S.L.U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67618454', 'PENTAGO XXI S.', 'Calle Bailen 50 Entresuelo-Primera', 'Barcelona', 'Barcelona', '8009', 'España'),
('PEPE ENERGY S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B87047064', 'PEPE ENERGY S.', 'Avenida de Bruselas 38', 'Alcobendas', 'Madrid', '28108', 'España'),
('PRISMICA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98845944', 'PRISMICA S.L.', 'C/METGE PANELLA Nº6', 'ALQUERIA DE LA COMTESSA', 'Valencia', '46715', 'España'),
('Promociones Nederval SA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46400362', 'Promociones Ned', 'Calle Zurbano-45-1', 'Madrid', 'Madrid', '28010', 'España'),
('PROUDLACES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B65386963', 'PROUDLACES S.L', 'Calle Maracaibo 5 - Nave 7', 'Barcelona', 'Barcelona', '8030', 'España'),
('RDIFUSIÃN S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B28620797', 'RDIFUSIÃN', 'C/ Conde de Cartagena 5 Bajo A', 'Madrid', 'Madrid', '28007', 'España'),
('RIBA GLOBAL SERVICES 2014 SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98641657', 'RIBA GLOBAL SER', 'Artes Gráficas 4', 'Valencia', 'Valencia', '46010', 'España'),
('RIVER TECH DIGITAL BV', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'NL859890065B01', 'RIVER TECH DIGI', 'Strawinskylaan 945', '1077 XX Amsterdam', NULL, NULL, NULL),
('RUNUCOM S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B90142555', 'RUNUCOM', 'Calle Espaldillas Ocho no 27', 'Alcalá de Guadaira', 'Sevilla', '41500', 'España'),
('SAMOVING S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B75237651', 'SAMOVING S.L.', 'Iñaki Goenaga 5', 'Eibar', 'Gipuzkoa', '20600', 'España'),
('SilverTours GmbH', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DE228971672', 'SilverTours Gmb', 'Holzmarkt 2a', '50676 Cologne Germany', NULL, NULL, NULL),
('SIMPLIFIO LTD', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SIMPLIFIO LTD', 'SECOND FLOOR ATLANTIC HOUSE CIRCULAR ROAD DOUGLAS', 'IM1 1AG Isle of Man', NULL, NULL, NULL),
('SINGULARU IDEAS A MEDIDA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98623937', 'SINGULARU IDEAS', 'Calle de la Foia 3', 'Picanya', 'Valencia', '46210', 'España'),
('SOLERS BEAUTY BUSINESS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98970551', 'SOLERS BEAUTY', 'C/ Mártires nº 31', 'L Alqueria de la Comtessa', 'Valencia', '46715', 'España'),
('SOMETHING TO SAY SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66858606', 'SOMETHING TO SA', 'C/ Gelabert 17 pral 2na', 'Barcelona', 'Barcelona', '8029', 'España'),
('SUBASTAS GEMA S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97209597', 'SUBASTAS GEMA', 'Calle La Paz 17 Bajo', 'Valencia', 'Valencia', '46003', 'España'),
('TEROL & SERNA ASOCIADOS S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B54730924', 'TEROL & SERNA A', 'Calle Zapateros 17 Nave', 'Aspe', 'Alicante', '3680', 'España'),
('THE COOKIE AFTERWORK S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42828608', 'THE COOKIE AFTE', 'Plaza Pablo Ruiz Picasso 1', 'Madrid', 'Madrid', '28020', 'España'),
('TIMPERS BRAND S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40650608', 'TIMPERS', 'Muelle de la aduana S/N Lanzadera Marina de Valencia', 'Valencia', 'Valencia', '46024', 'España'),
('TORNASOL LABS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B16788481', 'TORNASOL', 'Paseo de la alameda nº12bis 2-4', 'Valencia', 'Valencia', '46010', 'España'),
('UNWIND TECHNOLOGIES S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FR57903782480', 'UNWIND', 'Place d Armes 19', 'Carouge Switzerland', NULL, NULL, NULL),
('UTOPIG STUDIO S.C.C.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F67521773', 'UTOPIG STUDIO', 'Carrer de l''Abat Marcet 8 2n 1a', 'Sant Cugat del Vallés', 'Barcelona', '8173', 'España'),
('VENTA ONLINE JM TEXTIL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98466246', 'VENTA ONLINE JM', 'C/ Josep Gironesvalls 1a', 'ONTINYENT', 'Valencia', '46870', 'España'),
('VIVE ENERGIA ELECTRICA SA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A87705471', 'VIVE ENERGIA', 'Calle Príncipe de Vergara 35 Bajo Izq', 'Madrid', 'Madrid', '28001', 'España'),
('WHITE DIVISION S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B02997666', 'WHITE DIVISION', 'Calle Xixona no 3', 'Elche', 'Alicante', '3204', 'España'),
('WISE WEB SALE LTD', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'WISE WEB', 'PO Box 1510', 'Beachmont Kingstown', NULL, NULL, NULL),
('WONDERFLIP S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01755107', 'WONDERFLIP', 'Calle Galeón Edificio Sauce I', 'Torrevieja', 'Alicante', '3182', 'España'),
('ZUMEX DEUTSCHLAND GMBH', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DE312801079', 'ZUMEX DE', 'ELISABETHSTRABE 11', '217 DÃSSELDORF DÃSSELDORF', NULL, NULL, NULL),
('ZUMEX FRANCE SARL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FR65804982874', 'ZUMEX FR', 'Immeuble Panama Parc Tertiaire Silic 45 rue de Villeneuve', '94573 Rungis Cedex Paris', NULL, NULL, NULL),
('ZUMEX GROUP S.A.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46271326', 'ZUMEX GROUP', 'C/ MOLI Nº 2 POLIG IND MONCADA III', 'Moncada', 'Valencia', '46113', 'España'),
('ZUMEX Ltd.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GB157818573', 'ZUMEX Ltd.', '3 More London Riverside', 'SE1 2RE London London', NULL, NULL, NULL),
('ZUMEX MEXICO', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ZUMEX MEX', 'Uxmal 616 Colonia Vértiz Narvarte Delegación Benito Juárez', '3600 Ciudad de México Ciudad de México', NULL, NULL, NULL),
('ZUMEX USA INC', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ZUMEX USA', '1573 NW 82nd Ave', 'FL 33126-1 Miami Florida', NULL, NULL, NULL),
('MIS NOMAN SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67697649', 'F45', 'EDUARDO BENOT', 'SANTANDER', 'Santander', '39003', 'España'),
('UNREALITY S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B42882233', 'QUASARDYNAMICS', 'Doctor Oloriz', 'VALENCIA', 'Valencia', '46009', 'España'),
('EMPRENDIMIENTOS HOSTELEROS VALENCIA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98331887', 'STAYINGVALENCIA', 'Avenida Instituto Obrero 20', 'VALENCIA', 'Valencia', '46013', 'España'),
('CTAIMA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B43715812', 'CTAIMA', 'Salvador Espriu 18', 'TARRAGONA', 'Tarragona', '43007', 'España'),
('PRESSBROKERS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98346646', 'BITNOVO', 'Calle illa de Sardenya', 'VALENCIA', 'Valencia', '46023', 'España'),
('OUTVIO OU', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EST', 'OUTVIO OU', NULL, NULL, NULL, NULL, NULL),
('DARWIN MEDIA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B19328285', 'DARWIN MEDIA', 'Pico Ocejón', 'Villanueva de la Torre', NULL, NULL, NULL),
('ASISA DENTAL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A85403814', 'ASISA DENTAL', 'Juan Ignacio Luca de Tena', 'MADRID', 'Madrid', '28027', 'España'),
('ONESTIC INNOVACION Y DESARROLLO S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97954036', 'ONESTIC', 'Roger de Lauria', 'VALENCIA', 'Valencia', '46002', 'España'),
('PAYHAWK SPAIN S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B10616928', 'PAYHAWK SPAIN', 'Sancho de Avila', 'BARCELONA', 'Barcelona', '8018', 'España'),
('CUTERA FRANCE SARL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FR48444514152', 'CUTERA FRANCE S', '1 rue Georges Charpak bâtiment C', 'Lieusaint', NULL, '77127', 'España'),
('EINSTEIN TRAINING LDA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PT516095145', 'EINSTEIN TRAINI', NULL, 'Lisboa', NULL, '1050 234', NULL),
('MALPASO HOLDING S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B66788654', 'MALPASO HOLDING', 'Diputación', 'BARCELONA', 'Barcelona', '8009', 'España'),
('GIIR Germany GmbH', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DE815390050', 'GIIR Germany Gm', NULL, 'Eschborn', NULL, NULL, NULL),
('COFACE SERVICIOS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B82808767', 'COFACE SERVICIO', 'VIA DE LOS POBLADOS', 'MADRID', 'Madrid', '28033', 'España'),
('IBERICA FRUIT', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98915838', 'IBERICA FRUIT', 'de la Universidad', 'VALENCIA', 'Valencia', '46002', 'España'),
('BIZPILLS GROUP S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88248182', 'ISEAZY', 'Marqués de Monteagudo nº22 5B', 'MADRID', 'Madrid', '28028', 'España'),
('Asociación HABITALE', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G83253245', 'HABITALE', 'José Ortega y Gasset', 'MADRID', 'Madrid', '28006', 'España'),
('BE YOUR PACKER S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B06868905', 'Be Your Packer', 'Matarrosa 33 nave', 'FUENLABRADA', 'Madrid', '28947', 'España'),
('ALTONADOCK S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86227485', 'ALTONADOCK S.L', 'la Florida', 'VILLAVICIOSA DE ODON', 'Madrid', '28670', 'España'),
('HORIZON PROYECTOS ENERGETICOS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B12949459', 'PYLONDATA', 'Galicia', 'VINAROS', 'Castellón', '12500', 'España'),
('Fundación Marcelino Olaechea', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'R4601428H', 'Fundación Marce', 'Quevedo', 'VALENCIA', 'Valencia', '46001', 'España'),
('ACREDITA S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'J305362530', 'ACREDITA S.A', 'Fco. de Miranda Edif Parque Avila', NULL, 'Avila', NULL, 'España'),
('INSTITUTO VALENCIANO DE ARTE MODERNO', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Q9655140C', 'IVAM', 'Guillem de Castro', 'VALENCIA', 'Valencia', '46003', 'España'),
('AYUNTAMIENTO DE GANDIA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P4613300E', 'AYTO GANDIA', 'Mayor', 'GANDíA', 'Valencia', '46701', 'España'),
('CIM Formación Alicante SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B54070248', 'CIM', 'Maestro Bretón', 'ALACANT/ALICANTE', 'Alicante', '3004', 'España'),
('0800 LEADS LTD', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0800 LEADS LTD', 'SHELTON STREET', NULL, NULL, NULL, NULL),
('SATORISAN S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98268196', 'SATORISAN S.L', NULL, 'VALENCIA', 'Valencia', '46023', 'España'),
('PARCLICK S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86329984', 'PARCLICK S.L', NULL, 'MADRID', 'Madrid', '28006', 'España'),
('FUNDACIÃN DEL TEATRO REAL F.S.P.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G81352247', 'FUNDACIÃN DEL T', NULL, 'MADRID', 'Madrid', '28013', 'España'),
('VCCP SPAIN S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B86472933', 'VCCP SPAIN S.L', NULL, 'MADRID', 'Madrid', '28016', 'España'),
('Netcraft Digital Ltd', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '7155826456', 'Netcraft Digita', '275 New North Road Suite 1459', NULL, NULL, NULL, NULL),
('MG Agnesi Training S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B06794416', 'MG Agnesi Train', 'Consell de cent', 'BARCELONA', 'Barcelona', '8007', 'España'),
('MICUNA FAMILY BRANDS S.L.U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97956643', 'MICUNA FAMILY', 'Sueca', 'SOLLANA', 'Valencia', '46430', 'España'),
('IKESOL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40657728', 'IKESOL', 'Mestre Villar', 'GANDíA', 'Valencia', '46701', 'España'),
('STRINGSFIELD GUITARS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98964737', 'STRINGSFIELD', 'Los Pedrones', 'VALENCIA', 'Valencia', '46017', 'España'),
('RED DE NEGOCIOS FORMATIVOS S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B70303474', 'WIIKON', 'Princesa', 'MADRID', 'Madrid', '28008', 'España'),
('INTERNET UP GMBH', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DE318854014', 'Snapbuy®', 'Hermann-Weinhauser-Str 73', 'München', NULL, '81673', 'España'),
('JUNIORS M.D.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'R4600441B', 'JUNIORS M.D.', 'Senia', 'VALENCIA', 'Valencia', '46001', 'España'),
('UBAEFITNESS', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B61652376', 'EUROFITNESS', 'Venus', 'BARCELONA', 'Barcelona', '8012', 'España'),
('PELAYO TRINQUET SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B56587900', 'PELAYO TRINQUET', 'Pelayo', 'VALENCIA', 'Valencia', '46006', 'España'),
('FOM INSIGHTS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B01711738', 'FOM INSIGHTS SL', 'Muñoz Degrain', 'VALENCIA', 'Valencia', '46003', 'España'),
('PROSOLIA INTERNACIONAL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97961452', 'PROSOLIA INTERN', 'Viento', 'ALACANT/ALICANTE', 'Alicante', '3006', 'España'),
('AMENITIZ SOLUTIONS S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67096750', 'AMENITIZ SOLUTI', 'Urquinaona', 'BARCELONA', 'Barcelona', '8010', 'España'),
('OCEANSIX S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B56925167', 'OCEANSIX S.L', 'La Albufera', 'SILLA', 'Valencia', '46460', 'España'),
('ATAA INTERACTIVE S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73966277', 'ATAA INTERACTIV', 'Curva', 'AGUILAS', 'Murcia', '30880', 'España'),
('EAGLE COURTESY - UNIPESSOAL LDA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '513724320', 'EAGLE COURTESY', '5 de Outubro', 'Lisboa', NULL, NULL, NULL),
('MARSOL FRUITS SPAIN S.L.U', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73856874', 'MARSOL FRUITS S', 'Doctor Fleming', 'AGUILAS', 'Murcia', '30880', 'España'),
('PROSOLIA ESPAÃA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B97330898', 'PROSOLIA ESPAÃA', 'VIENTO', 'ALICANTE/ALACANT', 'Alicante', '3006', 'España'),
('CUTERA INC', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'CUTERA INC', '3240 Bayshore Blvd', 'Brisbane CA 94005', NULL, NULL, NULL),
('PROSOLIA PORTUGAL SA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'PT508382106', 'PROSOLIA PT', NULL, NULL, NULL, NULL, NULL),
('PROSOLIA FRANCIA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'FR90502188717', 'PROSOLIA FRANCI', '75116 Paris', NULL, NULL, NULL, NULL),
('PROSOLIA ITALIA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'IT02037480478', 'PROSOLIA ITALIA', NULL, NULL, NULL, NULL, NULL),
('FUNDACIÃN AMIGOS DEL TEATRO REAL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'G87648960', 'FATR', 'Isabel II', 'MADRID', 'Madrid', '28013', 'España'),
('MANIPULADOS DE CEBOLLAS Y DERIVADOS S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96776059', 'EUROCEBOLLAS', 'Alzira-La Garrofera km 3 2', 'ALZIRA', 'Valencia', '46600', 'España'),
('SUTERRA EUROPE BIOCONTROL S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B63760078', 'SUTERRA EUROPE', 'América', 'VALENCIA', 'Valencia', '46004', 'España'),
('ASESORÃA MÃDICO ESTÃTICA INTEGRAL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73709263', 'ASESORÃA MÃDICO', 'DEL BANCO', 'Cádiz', 'Cadiz', '11403', 'España'),
('DESARROLLO Y PROMOCION DE PADEL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98998255', 'Slinger Padel', 'Cirilo Amoros', 'VALENCIA', 'Valencia', '46004', 'España'),
('Bijaam 33 S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B19871656', 'Bijaam 33 S.L', 'DOCTOR FLEMING 1 4 B', 'AGUILAS', 'Murcia', '30880', 'España'),
('VAIVOLTA TRAVEL S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B16475386', 'NATTHIS', 'Barcas', NULL, 'Valencia', '46002', 'España'),
('TCM GOURMET 2012 SOCIEDAD LIMITADA.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40509663', 'TCM GOURMET', 'Tramuntana', 'Corbera', 'Valencia', '46612', 'España'),
('CAFES Y ALIMENTO SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98835325', 'RELINDAS', 'Andrés Segovia', 'Puzol', 'Valencia', '46530', 'España'),
('AUTO ESCUELAS JORDA - SOCIEDAD FRANQUICIADORA DE AUTOESCUELAS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98318777', 'JORDÃ', 'Blasco Ibañez', NULL, 'Valencia', '46010', 'España'),
('GRUPO AQUAREA SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B54155023', 'AQUAREA', 'Número 29', 'Paterna', 'Valencia', '46182', 'España'),
('MAR CHANCOSA SOCIEDAD LIMITADA.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40572422', 'MARCHANCOSA', 'Joan XXIII', NULL, 'Valencia', '46025', 'España'),
('CAMPING MARTIN GONZALEZ SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B96727557', 'COLVERT', 'Valladolid', NULL, 'Valencia', '46020', 'España'),
('MARTIN & FABIA SL.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98955305', 'CAMPING PUZOL', 'Valladolid', NULL, 'Valencia', '46020', 'España'),
('SUEÃO ENTRE TELAS SOCIEDAD LIMITADA.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67833277', 'SUENÃAENTRETELA', 'Escolano', NULL, 'Valencia', '46001', 'España'),
('IGUAL ROGER SOCIEDAD LIMITADA.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40584377', 'IGUAL ROGER SOC', 'CIRIL AMOROS', NULL, 'Valencia', '46004', 'España'),
('DASHA LIVING SPACE SL.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98848948', 'DASHA', 'CANOVAS DEL CASTILLO', NULL, 'Valencia', '46005', 'España'),
('LOGISTICA IDAM MEDITERRANEA SRL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40659369', 'AQUAIDAM', 'EL PINAR', 'RRIBAROJA DEL TURIA', 'Valencia', '46190', 'España'),
('AINEZAN S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B10902518', 'AINEZAN S.L.', 'Blai Bellver 9-2-6', 'Xativa', 'Valencia', '46800', 'España'),
('ICRONO NETWORK S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98252869', 'ICRONO NETWORK', 'Gran Via Marques del Turia 59-9', NULL, 'Valencia', '46005', 'España'),
('ULTRAVERSO GROUP S.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B72916232', 'ULTRAVERSO GROU', 'PRINCESA', 'MADRID', 'Madrid', '28008', 'España'),
('J1 ECOPROPERTIES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ECOHOMES', NULL, NULL, NULL, NULL, NULL),
('ALMACEN DE FONTANERIA Y FERRETERIA INDUSTRIAL NOGUEROLES ALBIACH S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B98975675', 'AFFNA', 'Blasco Ibañez', 'Turis', 'Valencia', '46389', 'España'),
('DERMOFARM', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A08283624', 'DERMOFARM', 'LEONARDO DA VINCE', 'Rubí', 'Barcelona', '8191', 'España'),
('RALYTEC MEDIA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B56276462', 'RALYTEC MEDIA', 'Cantabria', 'Los Corrales de Bueln', 'Cantabria', '39400', 'España'),
('ZIM Connections Ltd', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'ZIM Connections', NULL, NULL, NULL, NULL, NULL),
('AFOSXSOFA SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AFOSXSOFA SL', NULL, NULL, NULL, NULL, 'España'),
('AUTOCERTIFY OU', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EE102716755', 'AUTOCERTIFY OU', NULL, NULL, NULL, NULL, NULL),
('2011 TRESAES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2011 TRESAES S', NULL, NULL, NULL, NULL, 'España'),
('AD LEVANTE PARTS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'AD LEVANTE PART', NULL, NULL, NULL, NULL, 'España'),
('COMELSA', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A46156394', 'MILAR', 'Riu Turia', NULL, 'Valencia', '46210', 'España'),
('HAPPY BITES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B40651598', 'HAPPY BITES SL', 'San Antonio 30', 'Mislata', 'Valencia', '46920', 'España'),
('ANNOOK CONTRACT SOLUTIONS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B56135809', 'ANNOOK', 'Eslovaquia', 'SAN PEDRO DE ALCANTARA', 'Murcia', '29670', 'España'),
('KUBE DIGITAL BUSINESS SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B67603720', 'KUBE DIGITAL BU', 'Roger de Llúria', 'Barcelona', 'Barcelona', '8009', 'España'),
('AUNARA REAL ESTATE S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B19440726', 'AUNARA REAL EST', 'Castellana', NULL, 'Madrid', '28046', 'España'),
('JIT HOUSING S.L', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B95961215', 'JIT HOUSING S.', 'Bizkarreta Rivabellosa', NULL, 'Alava', '1213', 'España'),
('TURBO ENERGY S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A98569619', 'TURBO ENERGY S', 'América', NULL, 'Valencia', '46004', 'España'),
('UMBRELLA GLOBAL ENERGY S.A', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A98988819', 'UMBRELLA', 'Plaza de América 2 4º B', NULL, 'Valencia', '46004', 'España'),
('INFORGES IT SERVICES SL', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73526360', 'INFORGES IT SER', 'Vicente Aleixandre', NULL, 'Murcia', '30011', 'España'),
('OPENRED SOLUCIONES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B73610511', 'OPENRED SOLUCIO', 'Real Academia de Medicina', NULL, 'Murcia', '30009', 'España'),
('In Motion Cloud', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B88470000', 'In Motion Cloud', 'Collado del Viento', 'Madrid', 'Madrid', '28034', 'España'),
('EKONSTEAM S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B19904432', 'EKONSTEAM S.L.', 'Larrauri', 'Loiu Bizkaia', 'Bizcaya', '48180', 'España'),
('LUCE INNOVATIVE TECHNOLOGIES S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B47638002', 'LUCE INNOVATIVE', NULL, NULL, NULL, NULL, NULL),
('EL ARMARIO DE OLIVIA S.L.', 'Baja', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'B65679847', 'EL ARMARIO DE O', 'MUNTANER', 'Barcelona', 'Barcelona', '8021', 'España');

-- 5. Re-crear índice único parcial en CIF (solo donde CIF no es NULL)
CREATE UNIQUE INDEX empresas_cif_unique ON empresas (cif) WHERE cif IS NOT NULL;

COMMIT;
